language: node_js
node_js:
  - "0.10"
script:
  - "npm run build && npm run test && npm run integration"
notifications:
  irc:
    channels:
      - "irc.freenode.org#primus"
    on_success: change
    on_failure: change
