sudo: false
language: node_js
node_js:
  - "0.8"
  - "0.10"
  - "0.12"
  - "iojs"
before_install:
  - 'if [ "${TRAVIS_NODE_VERSION}" == "0.8" ]; then npm install -g npm@2.10.1; fi'
script:
  - "npm run test && npm run integration"
matrix:
  fast_finish: true
notifications:
  irc:
    channels:
      - "irc.freenode.org#primus"
    on_success: change
    on_failure: change
