language: node_js
sudo: required
dist: trusty
node_js:
  - "7"
  - "6"
  - "4"
script:
  - "npm run test && npm run integration"
matrix:
  fast_finish: true
notifications:
  irc:
    channels:
      - "irc.freenode.org#primus"
    on_success: change
    on_failure: change
