sudo: false
language: node_js
node_js:
  - "4"
  - "3"
  - "2"
  - "1"
  - "0.12"
  - "0.10"
addons:
  apt:
    sources:
      - "ubuntu-toolchain-r-test"
    packages:
      - "g++-4.8"
env:
  - "CXX=g++-4.8"
script:
  - "npm run test && npm run integration"
matrix:
  fast_finish: true
notifications:
  irc:
    channels:
      - "irc.freenode.org#primus"
    on_success: change
    on_failure: change
