language: node_js
dist: trusty
sudo: false
node_js:
  - "9"
  - "8"
  - "6"
  - "4"
script:
  - "npm run test && npm run integration"
matrix:
  fast_finish: true
notifications:
  irc:
    channels:
      - "irc.freenode.org#primus"
    on_success: change
    on_failure: change
